# This is the network config written by 'subiquity'
network:
  ethernets:
    enp1s0:
      dhcp4: true
    enp2s0:
      addresses:
        - 192.168.9.1/24
      dhcp4: no
      dhcp6: no
    enp3s0:
      addresses:
        - 192.168.26.1/24
      dhcp4: no
      dhcp6: no
  version: 2
